GL_DKPValues = {["epgp"] = 1,["gp_base"] = 0,["current_dkp_data"] = {
            ["adasdsa"] = {
                ["earned"] = 31.90,
                ["spent"] = 28.50,
                ["current"] = 1.12,
                ["last30"] = 0,
                ["last60"] = 2,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 28.50,
                ["epgp_pr_base"] = 1.12,
                },
            ["adyda"] = {
                ["earned"] = 19.80,
                ["spent"] = 10.80,
                ["current"] = 1.83,
                ["last30"] = 0,
                ["last60"] = 2,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 10.80,
                ["epgp_pr_base"] = 1.83,
                },
            ["aeglos"] = {
                ["earned"] = 10.80,
                ["spent"] = 0.00,
                ["current"] = 10.80,
                ["last30"] = 0,
                ["last60"] = 2,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 10.80,
                },
            ["alivastus"] = {
                ["earned"] = 10.80,
                ["spent"] = 12.00,
                ["current"] = 0.90,
                ["last30"] = 0,
                ["last60"] = 2,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 12.00,
                ["epgp_pr_base"] = 0.90,
                },
            ["alyrra"] = {
                ["earned"] = 14.40,
                ["spent"] = 346.50,
                ["current"] = 0.04,
                ["last30"] = 0,
                ["last60"] = 2,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 346.50,
                ["epgp_pr_base"] = 0.04,
                },
            ["ambrozia"] = {
                ["earned"] = 10.80,
                ["spent"] = 0.00,
                ["current"] = 10.80,
                ["last30"] = 0,
                ["last60"] = 2,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 10.80,
                },
            ["amorre"] = {
                ["earned"] = 10.80,
                ["spent"] = 0.00,
                ["current"] = 10.80,
                ["last30"] = 0,
                ["last60"] = 2,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 10.80,
                },
            ["anahne"] = {
                ["earned"] = 10.80,
                ["spent"] = 0.00,
                ["current"] = 10.80,
                ["last30"] = 0,
                ["last60"] = 2,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 10.80,
                },
            ["anarius"] = {
                ["earned"] = 0.00,
                ["spent"] = 60.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 6,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 60.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["angkor"] = {
                ["earned"] = 10.80,
                ["spent"] = 0.00,
                ["current"] = 10.80,
                ["last30"] = 0,
                ["last60"] = 2,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 10.80,
                },
            ["anihilation"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 3,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["anterior"] = {
                ["earned"] = 14.40,
                ["spent"] = 0.00,
                ["current"] = 14.40,
                ["last30"] = 0,
                ["last60"] = 2,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 14.40,
                },
            ["arbin"] = {
                ["earned"] = 10.80,
                ["spent"] = 0.00,
                ["current"] = 10.80,
                ["last30"] = 0,
                ["last60"] = 2,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 10.80,
                },
            ["archfiend"] = {
                ["earned"] = 10.80,
                ["spent"] = 0.00,
                ["current"] = 10.80,
                ["last30"] = 0,
                ["last60"] = 2,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 10.80,
                },
            ["astroo"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["attreides"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["bakalakadaka"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["bammabut"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["banquejunque"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["barrista"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["benitocamelo"] = {
                ["earned"] = 9.00,
                ["spent"] = 0.00,
                ["current"] = 9.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 9.00,
                },
            ["bias"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["bigbone"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["bkstacker"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["bollddrick"] = {
                ["earned"] = 0.00,
                ["spent"] = 120.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 6,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 120.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["bowlkin"] = {
                ["earned"] = 5.40,
                ["spent"] = 0.00,
                ["current"] = 5.40,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 5.40,
                },
            ["brambleclaw"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["brietta"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["burler"] = {
                ["earned"] = 3.60,
                ["spent"] = 157.50,
                ["current"] = 0.02,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 157.50,
                ["epgp_pr_base"] = 0.02,
                },
            ["cajun"] = {
                ["earned"] = 9.00,
                ["spent"] = 0.00,
                ["current"] = 9.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 9.00,
                },
            ["catrose"] = {
                ["earned"] = 3.60,
                ["spent"] = 0.00,
                ["current"] = 3.60,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 3.60,
                },
            ["ceecee"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["ceralyn"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["chickapea"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["chrusty"] = {
                ["earned"] = 9.00,
                ["spent"] = 110.70,
                ["current"] = 0.08,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 110.70,
                ["epgp_pr_base"] = 0.08,
                },
            ["cilginbambi"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["conienn"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["crentiz"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 3,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["cuelgate"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["cybelar"] = {
                ["earned"] = 3.60,
                ["spent"] = 415.80,
                ["current"] = 0.01,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 415.80,
                ["epgp_pr_base"] = 0.01,
                },
            ["daharkan"] = {
                ["earned"] = 3.60,
                ["spent"] = 0.00,
                ["current"] = 3.60,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 3.60,
                },
            ["dantilion"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["dehumanized"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["demonicdawl"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["dessirée"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 6,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["dethlyte"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["diasjc"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["dirtie"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["discostujc"] = {
                ["earned"] = -1.80,
                ["spent"] = 0.00,
                ["current"] = -1.80,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = -1.80,
                },
            ["dottii"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["dranzero"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 3,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["drawne"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["eava"] = {
                ["earned"] = 9.00,
                ["spent"] = 0.00,
                ["current"] = 9.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 9.00,
                },
            ["emii"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["emilea"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["etarnalazure"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 6,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["eupha"] = {
                ["earned"] = 9.00,
                ["spent"] = 0.00,
                ["current"] = 9.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 9.00,
                },
            ["eyka"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["fabrice"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["forsoning"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["geauxsaints"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["gizamet"] = {
                ["earned"] = 3.60,
                ["spent"] = 0.00,
                ["current"] = 3.60,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 3.60,
                },
            ["glon"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 6,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["grimtooth"] = {
                ["earned"] = 9.00,
                ["spent"] = 0.00,
                ["current"] = 9.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 9.00,
                },
            ["grimwolfe"] = {
                ["earned"] = 3.60,
                ["spent"] = 0.00,
                ["current"] = 3.60,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 3.60,
                },
            ["grishka"] = {
                ["earned"] = -1.80,
                ["spent"] = 0.00,
                ["current"] = -1.80,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = -1.80,
                },
            ["guildlaunch"] = {
                ["earned"] = 0.90,
                ["spent"] = 0.00,
                ["current"] = 0.90,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.90,
                },
            ["gunak"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["gundemin"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 6,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["haircopter"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["heartbreakr"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["herbal"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["hetra"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["huntin"] = {
                ["earned"] = -1.80,
                ["spent"] = 0.00,
                ["current"] = -1.80,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = -1.80,
                },
            ["icetorch"] = {
                ["earned"] = -1.80,
                ["spent"] = 0.00,
                ["current"] = -1.80,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = -1.80,
                },
            ["indocin"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["irisflower"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 6,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["jinglor"] = {
                ["earned"] = 0.00,
                ["spent"] = 60.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 6,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 60.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["johndunbar"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["josejc"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["jurassic"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["kaelris"] = {
                ["earned"] = -1.80,
                ["spent"] = 0.00,
                ["current"] = -1.80,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = -1.80,
                },
            ["kallysto"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["kaygel"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["keiyuro"] = {
                ["earned"] = -1.80,
                ["spent"] = 0.00,
                ["current"] = -1.80,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = -1.80,
                },
            ["kelanass"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["keridwen"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["khalija"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["klinkchillx"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["korinth"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["lausbube"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["lawlerberry"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["levati"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["linkan"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["lockycharms"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["loucyphr"] = {
                ["earned"] = 3.60,
                ["spent"] = 0.00,
                ["current"] = 3.60,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 3.60,
                },
            ["luciferatus"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["maariie"] = {
                ["earned"] = 3.60,
                ["spent"] = 0.00,
                ["current"] = 3.60,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 3.60,
                },
            ["madsdruid"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["malickjc"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["maniax"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["mannick"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["matronmurder"] = {
                ["earned"] = 3.60,
                ["spent"] = 0.00,
                ["current"] = 3.60,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 3.60,
                },
            ["maurlyn"] = {
                ["earned"] = -1.80,
                ["spent"] = 0.00,
                ["current"] = -1.80,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = -1.80,
                },
            ["maursdeath"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["maxpainê"] = {
                ["earned"] = 7.20,
                ["spent"] = 415.80,
                ["current"] = 0.02,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 415.80,
                ["epgp_pr_base"] = 0.02,
                },
            ["meatboss"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["melida"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["metrosexual"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["mirakodus"] = {
                ["earned"] = 3.60,
                ["spent"] = 0.00,
                ["current"] = 3.60,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 3.60,
                },
            ["mofodome"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 6,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["monan"] = {
                ["earned"] = -0.90,
                ["spent"] = 0.90,
                ["current"] = -0.90,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.90,
                ["epgp_pr_base"] = -1.00,
                },
            ["monanokay"] = {
                ["earned"] = 5.40,
                ["spent"] = 258.30,
                ["current"] = 0.02,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 258.30,
                ["epgp_pr_base"] = 0.02,
                },
            ["moochie"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["moonshardz"] = {
                ["earned"] = 3.60,
                ["spent"] = 0.00,
                ["current"] = 3.60,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 3.60,
                },
            ["mortie"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["mspaine"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["murasama"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["nabir"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["nappa"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 6,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["narttu"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 6,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["nelth"] = {
                ["earned"] = 3.60,
                ["spent"] = 0.00,
                ["current"] = 3.60,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 3.60,
                },
            ["nvrseventy"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["nyquil"] = {
                ["earned"] = -1.80,
                ["spent"] = 0.00,
                ["current"] = -1.80,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = -1.80,
                },
            ["obothegreat"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["onka"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["oojitsu"] = {
                ["earned"] = 5.40,
                ["spent"] = 0.00,
                ["current"] = 5.40,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 5.40,
                },
            ["painbearer"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["palidout"] = {
                ["earned"] = -1.80,
                ["spent"] = 0.00,
                ["current"] = -1.80,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = -1.80,
                },
            ["papateppic"] = {
                ["earned"] = -1.80,
                ["spent"] = 0.00,
                ["current"] = -1.80,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = -1.80,
                },
            ["pearil"] = {
                ["earned"] = -1.80,
                ["spent"] = 0.00,
                ["current"] = -1.80,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = -1.80,
                },
            ["pendaca"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["phipbones"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["phoj"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["pixiestiks"] = {
                ["earned"] = 3.60,
                ["spent"] = 0.00,
                ["current"] = 3.60,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 3.60,
                },
            ["prognome"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 3,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["puffpuffpas"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["rabin"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["rakron"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["razzinda"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["reztips"] = {
                ["earned"] = -1.80,
                ["spent"] = 0.00,
                ["current"] = -1.80,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = -1.80,
                },
            ["riftjumper"] = {
                ["earned"] = 3.60,
                ["spent"] = 0.00,
                ["current"] = 3.60,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 3.60,
                },
            ["ródi"] = {
                ["earned"] = 0.00,
                ["spent"] = 60.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 6,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 60.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["roflcone"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["roguezone"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["rothunter"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["ryanjm"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 3,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["sabroninim"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["saerian"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["saintavalon"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["saintsdeath"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["saintstouch"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["sajen"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 6,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["sdfds"] = {
                ["earned"] = -1.80,
                ["spent"] = 0.00,
                ["current"] = -1.80,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = -1.80,
                },
            ["sedo"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["serafym"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["serendipity"] = {
                ["earned"] = -1.80,
                ["spent"] = 0.00,
                ["current"] = -1.80,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = -1.80,
                },
            ["sevenofone"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["sfdsfsd"] = {
                ["earned"] = -1.80,
                ["spent"] = 0.00,
                ["current"] = -1.80,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = -1.80,
                },
            ["sfdsfsddd"] = {
                ["earned"] = -1.80,
                ["spent"] = 0.00,
                ["current"] = -1.80,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = -1.80,
                },
            ["shortstory"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["sinmania"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["sivle"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["skeeterbugz"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["skillitor"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["snipethis"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["spitzbube"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["steelz"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["suppafly"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["takis"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["tass"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["tayaris"] = {
                ["earned"] = -1.80,
                ["spent"] = 0.00,
                ["current"] = -1.80,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = -1.80,
                },
            ["thallandor"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["theheatt"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["thoridian"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 6,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["thyme"] = {
                ["earned"] = -1.80,
                ["spent"] = 0.00,
                ["current"] = -1.80,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = -1.80,
                },
            ["tiquortoo"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["tiquortres"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["tolliver"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["tolpatsch"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["trofski"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["turock"] = {
                ["earned"] = 3.60,
                ["spent"] = 441.00,
                ["current"] = 0.01,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 441.00,
                ["epgp_pr_base"] = 0.01,
                },
            ["twinyooper"] = {
                ["earned"] = 3.60,
                ["spent"] = 0.00,
                ["current"] = 3.60,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 3.60,
                },
            ["tyrinthya"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["tyrna"] = {
                ["earned"] = 5.40,
                ["spent"] = 0.00,
                ["current"] = 5.40,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 5.40,
                },
            ["underath"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["uraeus"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["vailia"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 6,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["vanstin"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["vauda"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["vigilancer"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 6,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["vozhd"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["wartest"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["whistlér"] = {
                ["earned"] = 0.00,
                ["spent"] = 60.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 6,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 60.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["wierd"] = {
                ["earned"] = -1.80,
                ["spent"] = 0.00,
                ["current"] = -1.80,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = -1.80,
                },
            ["wonk"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["wookster"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 6,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["xriin"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["xuthracht"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["yodus"] = {
                ["earned"] = 3.60,
                ["spent"] = 0.00,
                ["current"] = 3.60,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 3.60,
                },
            ["yoman"] = {
                ["earned"] = 0.00,
                ["spent"] = 0.00,
                ["current"] = 0.00,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = 0.00,
                },
            ["zangetzu"] = {
                ["earned"] = -1.80,
                ["spent"] = 0.00,
                ["current"] = -1.80,
                ["last30"] = 0,
                ["last60"] = 0,
                ["guildlast30"] = 1,
                ["guildlast60"] = 9,        
                ["epgp_gp_base"] = 0.00,
                ["epgp_pr_base"] = -1.80,
                },},};